export const ColorLibrary = {
  "#ffffff": "stark spirit",
  "#f0f8ff": "infinite frost",
  "#faebd7": "ancient echo",
  "#00ffff": "electric gallop",
  "#7fffd4": "river spirit",
  "#f0ffff": "luminous breath",
  "#f5f5dc": "wild oat",
  "#ffe4c4": "dawn prairie",
  "#000000": "void gallop",
  "#0000ff": "universal depth",
  "#8a2be2": "wild thistle",
  "#a52a2a": "earth pulse",
  "#deb887": "woven grass",
  "#5f9ea0": "distant horizon",
  "#7fff00": "raw pasture",
  "#d2691e": "warm hide",
  "#ff7f50": "desert spark",
  "#6495ed": "boundless sky",
  "#fff8dc": "spirit seed",
  "#dc143c": "inner pulse",
  "#00008b": "midnight herd",
  "#008b8b": "ancient stream",
  "#b8860b": "golden mane",
  "#a9a9a9": "misty coat",
  "#006400": "sacred forest",
  "#bdb76b": "wild dune",
  "#8b008b": "cosmic purple",
  "#556b2f": "untamed moss",
  "#ff8c00": "burning coat",
  "#9932cc": "unbound light",
  "#8b0000": "primal blood",
  "#e9967a": "red earth",
  "#8fbc8f": "sage breath",
  "#483d8b": "twilight gait",
  "#2f4f4f": "obsidian wind",
  "#00ced1": "unheld water",
  "#9400d3": "astral pony",
  "#ff1493": "fuchsia flame",
  "#00bfff": "free stream",
  "#696969": "storm cloud",
  "#1e90ff": "shining horizon",
  "#b22222": "deep ember",
  "#fffaf0": "pale colt",
  "#228b22": "deep green run",
  "#ff00ff": "neon spark",
  "#dcdcdc": "silver shimmer",
  "#f8f8ff": "winter light",
  "#ffd700": "solar mane",
  "#daa520": "golden buckskin",
  "#808080": "dusty trail",
  "#008000": "clover field",
  "#adff2f": "first blade",
  "#f0fff0": "sweet air",
  "#ff69b4": "velvet nose",
  "#cd5c5c": "sorrel fire",
  "#4b0082": "deep cosmos",
  "#fffff0": "ivory light",
  "#f0e68c": "sunlight mane",
  "#e6e6fa": "lavender breath",
  "#fff0f5": "soft muzzle",
  "#7cfc00": "wild herb",
  "#fffacd": "lemon spark",
  "#add8e6": "cool spirit",
  "#f08080": "roan fire",
  "#e0ffff": "ethereal air",
  "#fafad2": "pale light",
  "#d3d3d3": "smoky gait",
  "#90ee90": "apple light",
  "#ffb6c1": "wild bloom",
  "#ffa07a": "ranch dawn",
  "#20b2aa": "teal tide",
  "#87cefa": "open air",
  "#778899": "steel spirit",
  "#b0c4de": "riderless blue",
  "#ffffe0": "flaxen glow",
  "#00ff00": "lush grazing",
  "#32cd32": "racing green",
  "#faf0e6": "pale linen",
  "#800000": "dark cedar",
  "#66cdaa": "minty herb",
  "#0000cd": "ocean run",
  "#ba55d3": "heather hill",
  "#9370db": "purple pasture",
  "#3cb371": "meadow grass",
  "#7b68ee": "violet veil",
  "#00fa9a": "spring gallop",
  "#48d1cc": "turquoise tide",
  "#c71585": "berry light",
  "#191970": "midnight moon",
  "#f5fffa": "clean spirit",
  "#ffe4e1": "apricot light",
  "#ffe4b5": "toasted sun",
  "#ffdead": "raw earth",
  "#000080": "deep navy",
  "#fdf5e6": "old spirit",
  "#808000": "olive grove",
  "#6b8e23": "wild mule",
  "#ffa500": "wild carrot",
  "#ff4500": "burning blaze",
  "#da70d6": "wild orchid",
  "#eee8aa": "sandy plain",
  "#98fb98": "pale field",
  "#afeeee": "spirit ice",
  "#db7093": "pink spirit",
  "#ffefd5": "cloud cream",
  "#ffdab9": "peach light",
  "#cd853f": "copper run",
  "#ffc0cb": "cotton bloom",
  "#dda0dd": "plum spirit",
  "#b0e0e6": "powder air",
  "#800080": "purple flow",
  "#663399": "royal spirit",
  "#ff0000": "pure pulse",
  "#bc8f8f": "rosy roan",
  "#4169e1": "unheld gallop",
  "#8b4513": "cedar hide",
  "#fa8072": "salmon leap",
  "#f4a460": "sandy flank",
  "#2e8b57": "sea grass",
  "#fff5ee": "spirit shell",
  "#a0522d": "sienna spirit",
  "#c0c0c0": "silver light",
  "#87ceeb": "sky spirit",
  "#6a5acd": "slate stallion",
  "#708090": "slate mare",
  "#fffafa": "snowy light",
  "#00ff7f": "spring sprout",
  "#4682b4": "steel spirit",
  "#d2b48c": "tan earth",
  "#008080": "teal trail",
  "#d8bfd8": "thistle field",
  "#ff6347": "warm treat",
  "#40e0d0": "turquoise flow",
  "#ee82ee": "violet spirit",
  "#f5deb3": "wheat run",
  "#f5f5f5": "white wind",
  "#ffff00": "yellow bloom",
  "#9acd32": "green gallop",
};

export const getNearestColorName = (hex) => {
  if (!hex) return "this hue";
  const hexToRgb = (h) => {
    const fullHex =
      h.length === 4 ? "#" + h[1] + h[1] + h[2] + h[2] + h[3] + h[3] : h;
    const r = parseInt(fullHex.substring(1, 3), 16);
    const g = parseInt(fullHex.substring(3, 5), 16);
    const b = parseInt(fullHex.substring(5, 7), 16);
    return { r, g, b };
  };

  const target = hexToRgb(hex);
  let minDistance = Infinity;
  let bestName = "this hue";

  for (const [libHex, name] of Object.entries(ColorLibrary)) {
    const libRgb = hexToRgb(libHex);
    const distance = Math.sqrt(
      Math.pow(target.r - libRgb.r, 2) +
        Math.pow(target.g - libRgb.g, 2) +
        Math.pow(target.b - libRgb.b, 2),
    );
    if (distance < minDistance) {
      minDistance = distance;
      bestName = name;
    }
  }
  return bestName;
};
